<?php
$title = 'Добавить новый альбом';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo '<div class="form-group">' . $this->formRow($form->get('album')->get('title')) . '</div>';
echo '<div class="form-group">' . $this->formRow($form->get('album')->get('artistTitle')) . '</div>';
echo $this->formSubmit($form->get('album')->get('submit'));
echo $this->form()->closeTag();
